// reportExport.js - render a report's markdown to PDF and Word.
//
// Split out of the AIForm utils module, which also holds React components, antd and the
// mermaid runtime; nothing in the export path could be exercised outside a browser. This
// module imports only jspdf/docx/file-saver plus two pure helpers, so the document builders
// can be driven from plain Node and the generated bytes inspected.
//
// Parsing lives in markdownStructure.js and uses the same libraries the website renders with,
// so the exported document matches what the reader sees on screen.

import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, ExternalHyperlink, Table, TableCell, TableRow, HeadingLevel, WidthType, ImageRun } from 'docx';
// file-saver is CommonJS; the default-import form is the one that works both under Meteor and
// under plain Node ESM, which the document builders are exercised from.
import fileSaver from 'file-saver';

// Extensions are explicit so these modules also resolve under plain Node ESM, which is how
// the generated PDF/DOCX get inspected outside a browser.
import { parseMarkdownToStructure } from './markdownStructure.js';
import { normalizeMermaidCode } from './mermaidCode.js';

// Normalize Unicode characters to ASCII for PDF compatibility
const normalizeUnicode = (text) => {
    if (!text) return '';
    return text
        // Invisible/zero-width characters (must be first)
        .replace(/[\u200B\u200C\u200D\uFEFF\uFE0F]/g, '')  // Zero-width space, joiner, etc.
        // Special spaces
        .replace(/[\u00A0\u202F\u2007]/g, ' ')  // Non-breaking space, narrow no-break space
        // Non-breaking hyphens and dashes
        .replace(/[\u2010\u2011\u2012\u2013\u2014\u2015]/g, '-')
        // Arrows
        .replace(/→/g, '->')
        .replace(/←/g, '<-')
        .replace(/↑/g, '^')
        .replace(/↓/g, 'v')
        .replace(/↔/g, '<->')
        // Check marks and status symbols
        .replace(/[✓✔]/g, 'YES')
        .replace(/[✗✘]/g, 'NO')
        .replace(/[✅]/g, '[YES]')
        .replace(/[❌]/g, '[NO]')
        .replace(/[⚠️⚠]/g, '[!]')
        .replace(/[ℹ️ℹ]/g, '[i]')
        // Stars and special markers
        .replace(/⭐/g, '*')
        .replace(/★/g, '*')
        .replace(/☆/g, '*')
        // Greek letters (lowercase)
        .replace(/α/g, 'alpha')
        .replace(/β/g, 'beta')
        .replace(/γ/g, 'gamma')
        .replace(/δ/g, 'delta')
        .replace(/ε/g, 'epsilon')
        .replace(/ζ/g, 'zeta')
        .replace(/η/g, 'eta')
        .replace(/θ/g, 'theta')
        .replace(/ι/g, 'iota')
        .replace(/κ/g, 'kappa')
        .replace(/λ/g, 'lambda')
        .replace(/μ/g, 'mu')
        .replace(/ν/g, 'nu')
        .replace(/ξ/g, 'xi')
        .replace(/π/g, 'pi')
        .replace(/ρ/g, 'rho')
        .replace(/σ/g, 'sigma')
        .replace(/τ/g, 'tau')
        .replace(/υ/g, 'upsilon')
        .replace(/φ/g, 'phi')
        .replace(/χ/g, 'chi')
        .replace(/ψ/g, 'psi')
        .replace(/ω/g, 'omega')
        // Greek letters (uppercase)
        .replace(/Α/g, 'Alpha')
        .replace(/Β/g, 'Beta')
        .replace(/Γ/g, 'Gamma')
        .replace(/Δ/g, 'Delta')
        .replace(/Ε/g, 'Epsilon')
        .replace(/Ζ/g, 'Zeta')
        .replace(/Η/g, 'Eta')
        .replace(/Θ/g, 'Theta')
        .replace(/Λ/g, 'Lambda')
        .replace(/Μ/g, 'Mu')
        .replace(/Ξ/g, 'Xi')
        .replace(/Π/g, 'Pi')
        .replace(/Σ/g, 'Sigma')
        .replace(/Φ/g, 'Phi')
        .replace(/Ψ/g, 'Psi')
        .replace(/Ω/g, 'Omega')
        // Superscripts
        .replace(/⁰/g, '0')
        .replace(/¹/g, '1')
        .replace(/²/g, '2')
        .replace(/³/g, '3')
        .replace(/⁴/g, '4')
        .replace(/⁵/g, '5')
        .replace(/⁶/g, '6')
        .replace(/⁷/g, '7')
        .replace(/⁸/g, '8')
        .replace(/⁹/g, '9')
        .replace(/⁺/g, '+')
        .replace(/⁻/g, '-')
        // Subscripts
        .replace(/₀/g, '0')
        .replace(/₁/g, '1')
        .replace(/₂/g, '2')
        .replace(/₃/g, '3')
        .replace(/₄/g, '4')
        .replace(/₅/g, '5')
        .replace(/₆/g, '6')
        .replace(/₇/g, '7')
        .replace(/₈/g, '8')
        .replace(/₉/g, '9')
        .replace(/₊/g, '+')
        .replace(/₋/g, '-')
        // Math symbols
        .replace(/≥/g, '>=')
        .replace(/≤/g, '<=')
        .replace(/≠/g, '!=')
        .replace(/≈/g, '~=')
        .replace(/±/g, '+/-')
        .replace(/×/g, 'x')
        .replace(/÷/g, '/')
        .replace(/∞/g, 'infinity')
        .replace(/∑/g, 'sum')
        .replace(/∫/g, 'integral')
        .replace(/∂/g, 'partial')
        .replace(/√/g, 'sqrt')
        // Fractions
        .replace(/½/g, '1/2')
        .replace(/⅓/g, '1/3')
        .replace(/⅔/g, '2/3')
        .replace(/¼/g, '1/4')
        .replace(/¾/g, '3/4')
        // Degrees and special symbols
        .replace(/°/g, ' degrees')
        .replace(/℃/g, ' degrees C')
        .replace(/℉/g, ' degrees F')
        .replace(/…/g, '...')
        .replace(/—/g, '--')
        // Quotes
        .replace(/[""]/g, '"')
        .replace(/['']/g, "'")
        // Bullet points and special characters
        .replace(/[•●◆■]/g, '-')
        .replace(/·/g, '.')
        .replace(/†/g, '+')
        .replace(/‡/g, '++')
        // Currency (if any)
        .replace(/€/g, 'EUR')
        .replace(/£/g, 'GBP')
        .replace(/¥/g, 'YEN')
        // Final fallback: remove any remaining non-ASCII characters
        .replace(/[^\x00-\x7F]/g, '')
        ;
};

// DOCX is UTF-8, so real Unicode goes through untouched -- unlike the PDF path, Word has no
// reason to transliterate Greek letters or delete subscripts. Strip only what corrupts the
// file: zero-width characters, and control characters that are invalid in XML 1.0 and
// therefore in word/document.xml, which Word refuses to open.
const ZERO_WIDTH = /[\u200B\u200C\u200D\uFEFF]/g;
const XML_INVALID_CONTROL = /[\x00-\x08\x0B\x0C\x0E-\x1F]/g;   // keeps \t \n \r
const LONE_SURROGATE = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g;

const sanitizeForDocx = (text) => (text || '')
    .replace(ZERO_WIDTH, '')
    .replace(XML_INVALID_CONTROL, '')
    .replace(LONE_SURROGATE, '');

// Convert SVG string to PNG base64 (faster method)
const svgToPng = (svgString) => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(svgBlob);

        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width * 2; // 2x for better quality
            canvas.height = img.height * 2;

            const ctx = canvas.getContext('2d');
            ctx.scale(2, 2);
            ctx.fillStyle = 'white';
            ctx.fillRect(0, 0, img.width, img.height);
            ctx.drawImage(img, 0, 0);

            const pngDataUrl = canvas.toDataURL('image/png');
            URL.revokeObjectURL(url);

            resolve({
                dataUrl: pngDataUrl,
                width: img.width,
                height: img.height
            });
        };

        img.onerror = (error) => {
            URL.revokeObjectURL(url);
            reject(error);
        };

        img.src = url;
    });
};

// Extract already-rendered Mermaid diagrams from the DOM (FAST!)
const extractRenderedDiagrams = async () => {
    console.log('[Export] Extracting rendered diagrams...');
    const diagrams = [];

    // Find all rendered Mermaid SVGs in the document
    const svgElements = document.querySelectorAll('svg[id^="mermaid-"]');
    console.log('[Export] Found', svgElements.length, 'SVG elements');

    // If no SVGs found, try looking in the markdown content area
    if (svgElements.length === 0) {
        const markdownArea = document.querySelector('.markdown-with-refs');
        if (markdownArea) {
            const svgsInMarkdown = markdownArea.querySelectorAll('svg');
            console.log('[Export] Found', svgsInMarkdown.length, 'SVGs in markdown area');

            for (const svg of svgsInMarkdown) {
                try {
                    const svgClone = svg.cloneNode(true);
                    const serializer = new XMLSerializer();
                    const svgString = serializer.serializeToString(svgClone);

                    console.log('[Export] Converting SVG', diagrams.length + 1);
                    const diagram = await Promise.race([
                        svgToPng(svgString),
                        new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 5000))
                    ]);
                    diagrams.push(diagram);
                    console.log('[Export] Converted successfully');
                } catch (error) {
                    console.error('[Export] Failed to extract diagram:', error);
                }
            }
        }
    } else {
        for (const svg of svgElements) {
            try {
                const svgClone = svg.cloneNode(true);
                const serializer = new XMLSerializer();
                const svgString = serializer.serializeToString(svgClone);

                console.log('[Export] Converting SVG', diagrams.length + 1);
                const diagram = await Promise.race([
                    svgToPng(svgString),
                    new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 5000))
                ]);
                diagrams.push(diagram);
                console.log('[Export] Converted successfully');
            } catch (error) {
                console.error('[Export] Failed to extract diagram:', error);
            }
        }
    }

    console.log('[Export] Total diagrams extracted:', diagrams.length);
    return diagrams;
};

// Pre-render all Mermaid diagrams using Mermaid.ink API with high resolution config
const preRenderMermaidDiagrams = async (structure) => {
    const diagramMap = {};

    // Find all Mermaid code blocks
    const mermaidBlocks = structure
        .map((element, index) => ({ element, index }))
        .filter(({ element }) => element.type === 'code' && element.language === 'mermaid');

    if (mermaidBlocks.length === 0) {
        console.log('[Export] No Mermaid diagrams found');
        return diagramMap;
    }

    console.log(`[Export] Rendering ${mermaidBlocks.length} Mermaid diagram(s) via Mermaid.ink API (high-res)...`);

    // Render each diagram via Mermaid.ink API
    for (const { element, index } of mermaidBlocks) {
        try {
            console.log(`[Export] Rendering diagram ${index + 1}/${mermaidBlocks.length}...`);

            // Normalize the Mermaid code (remove Unicode, fix parentheses)
            const normalizedContent = normalizeMermaidCode(element.content);

            // Add high-resolution config to Mermaid code (larger fontSize = higher resolution)
            const highResConfig = `%%{init: {'theme':'default', 'themeVariables': {'fontSize':'32px', 'fontFamily':'Arial'}, 'flowchart': {'htmlLabels': false}}}%%\n`;

            // Check if diagram already has init config
            const hasInitConfig = normalizedContent.trim().startsWith('%%{init:');
            const mermaidCodeWithConfig = hasInitConfig ? normalizedContent : highResConfig + normalizedContent;

            // Encode Mermaid code to base64
            const base64Code = btoa(unescape(encodeURIComponent(mermaidCodeWithConfig)));
            const imageUrl = `https://mermaid.ink/img/${base64Code}`;

            // Fetch the image
            const response = await fetch(imageUrl);
            if (!response.ok) {
                throw new Error(`Failed to fetch diagram: ${response.statusText}`);
            }

            const blob = await response.blob();

            // Convert blob to data URL
            const dataUrl = await new Promise((resolve, reject) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result);
                reader.onerror = reject;
                reader.readAsDataURL(blob);
            });

            // Get image dimensions
            const img = new Image();
            await new Promise((resolve, reject) => {
                img.onload = resolve;
                img.onerror = reject;
                img.src = dataUrl;
            });

            diagramMap[index] = {
                dataUrl: dataUrl,
                width: img.width,
                height: img.height
            };

            console.log(`[Export] ✓ Diagram ${index + 1} rendered (${img.width}x${img.height}px)`);
        } catch (error) {
            console.error(`[Export] Failed to render diagram ${index + 1}:`, error.message);
            // Continue with other diagrams even if one fails
        }
    }

    console.log(`[Export] Successfully rendered ${Object.keys(diagramMap).length}/${mermaidBlocks.length} diagram(s)`);
    return diagramMap;
};

// ---------------------------------------------------------------------------------------
// PDF rendering
// ---------------------------------------------------------------------------------------

const PDF_LINK_COLOR = [21, 101, 192];

const runFontStyle = (run) => {
    if (run?.bold && run?.italic) return 'bolditalic';
    if (run?.bold) return 'bold';
    if (run?.italic) return 'italic';
    return 'normal';
};

const applyRunFont = (pdf, run, fontSize) => {
    pdf.setFontSize(fontSize);
    pdf.setFont(run?.code ? 'courier' : 'helvetica', runFontStyle(run));
};

// Break a run list into words and wrap opportunities, carrying each piece's formatting with
// it so a line can change font partway through.
const tokenizeRuns = (runs) => {
    const tokens = [];

    (runs || []).forEach(run => {
        const text = normalizeUnicode(run.text);
        text.split(/(\n|[ \t]+)/).forEach(part => {
            if (part === '') return;
            if (part === '\n') tokens.push({ type: 'break' });
            else if (/^[ \t]+$/.test(part)) tokens.push({ type: 'space', text: ' ', run });
            else tokens.push({ type: 'word', text: part, run });
        });
    });

    return tokens;
};

// A single token wider than the column (a long pathway identifier, say) still has to fit.
const splitOversizedWord = (pdf, token, maxWidth, fontSize) => {
    applyRunFont(pdf, token.run, fontSize);
    const pieces = [];
    let current = '';

    for (const character of token.text) {
        if (current && pdf.getTextWidth(current + character) > maxWidth) {
            pieces.push(current);
            current = character;
        } else {
            current += character;
        }
    }
    if (current) pieces.push(current);

    return pieces.map(text => ({ ...token, text, width: pdf.getTextWidth(text) }));
};

const layoutRuns = (pdf, runs, maxWidth, fontSize) => {
    const lines = [[]];
    let lineWidth = 0;

    const startLine = () => { lines.push([]); lineWidth = 0; };
    const currentLine = () => lines[lines.length - 1];

    tokenizeRuns(runs).forEach(token => {
        if (token.type === 'break') { startLine(); return; }

        applyRunFont(pdf, token.run, fontSize);
        const width = pdf.getTextWidth(token.text);

        if (token.type === 'space') {
            if (currentLine().length === 0) return;   // never open a line with a space
            currentLine().push({ ...token, width });
            lineWidth += width;
            return;
        }

        if (width > maxWidth) {
            if (currentLine().length > 0) startLine();
            splitOversizedWord(pdf, token, maxWidth, fontSize).forEach(piece => {
                currentLine().push(piece);
                startLine();
            });
            return;
        }

        if (lineWidth + width > maxWidth && currentLine().length > 0) {
            while (currentLine().length && currentLine()[currentLine().length - 1].type === 'space') {
                lineWidth -= currentLine().pop().width;
            }
            startLine();
        }

        currentLine().push({ ...token, width });
        lineWidth += width;
    });

    // Drop only the trailing empties the wrapper leaves behind; an empty line in the middle is
    // a deliberate blank line and has to stay.
    while (lines.length > 1 && lines[lines.length - 1].length === 0) lines.pop();
    return lines;
};

const drawRunLines = (pdf, lines, { x, y, lineHeight, ensureSpace }) => {
    let cursorY = y;

    lines.forEach(line => {
        cursorY = ensureSpace ? ensureSpace(cursorY, lineHeight) : cursorY;
        let cursorX = x;

        line.forEach(token => {
            applyRunFont(pdf, token.run, token.fontSize);
            if (token.run?.link) pdf.setTextColor(...PDF_LINK_COLOR);
            else pdf.setTextColor(0, 0, 0);
            pdf.text(token.text, cursorX, cursorY);

            // jsPDF has no strikethrough of its own, so draw the rule the browser would.
            if (token.run?.strike && token.type === 'word') {
                pdf.setDrawColor(0, 0, 0);
                pdf.setLineWidth(0.2);
                pdf.line(cursorX, cursorY - (token.fontSize || 10) * 0.1, cursorX + token.width, cursorY - (token.fontSize || 10) * 0.1);
            }

            cursorX += token.width;
        });

        cursorY += lineHeight;
    });

    pdf.setTextColor(0, 0, 0);
    pdf.setFont('helvetica', 'normal');
    return cursorY;
};

const withFontSize = (lines, fontSize) => lines.map(line => line.map(token => ({ ...token, fontSize })));

const drawRuns = (pdf, runs, options) => {
    const lines = withFontSize(layoutRuns(pdf, runs, options.maxWidth, options.fontSize), options.fontSize);
    return drawRunLines(pdf, lines, options);
};

/**
 * Build the PDF document. Separated from exportToPDF so the bytes can be produced and
 * inspected without a browser download.
 */
export const buildPdfDocument = async (markdown, options = {}) => {
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const structure = parseMarkdownToStructure(markdown);
    const diagramMap = options.diagramMap || await preRenderMermaidDiagrams(structure);

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    const maxWidth = pageWidth - (margin * 2);
    let yPos = 20;

    const ensureSpace = (y, neededHeight) => {
        if (y + neededHeight > pageHeight - margin) {
            pdf.addPage();
            return 20;
        }
        return y;
    };

    structure.forEach((element, index) => {
        if (element.type === 'heading') {
            const fontSize = element.level === 1 ? 18 : element.level === 2 ? 14 : 12;
            // Headings need air above them, the way the browser's margin-top gives them.
            if (index > 0) yPos += fontSize * 0.45;
            // Reserve room for a few lines of what follows too, so a heading is never left
            // stranded at the foot of a page.
            yPos = ensureSpace(yPos, fontSize / 2.2 + 14);
            yPos = drawRuns(pdf, element.runs.map(run => ({ ...run, bold: true })), {
                x: margin, y: yPos, maxWidth, fontSize, lineHeight: fontSize / 2.2, ensureSpace
            });
            yPos += 3;
        } else if (element.type === 'paragraph') {
            const indent = element.blockquote ? 6 : 0;
            const runs = element.blockquote
                ? element.runs.map(run => ({ ...run, italic: true }))
                : element.runs;

            yPos = ensureSpace(yPos, 10);
            const startY = yPos;
            yPos = drawRuns(pdf, runs, {
                x: margin + indent, y: yPos, maxWidth: maxWidth - indent,
                fontSize: 10, lineHeight: 4.5, ensureSpace
            });

            // A quoted passage gets the rule the browser draws down its left edge.
            if (element.blockquote && yPos > startY) {
                pdf.setDrawColor(180, 180, 180);
                pdf.setLineWidth(0.6);
                pdf.line(margin + 2, startY - 3.2, margin + 2, yPos - 4.2);
                pdf.setDrawColor(0, 0, 0);
            }
            yPos += 2;
        } else if (element.type === 'list') {
            const indent = 5 + (element.depth || 0) * 5;
            const markerWidth = 6;

            yPos = ensureSpace(yPos, 8);
            pdf.setFontSize(10);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(0, 0, 0);
            pdf.text(element.marker, margin + indent, yPos);

            yPos = drawRuns(pdf, element.runs, {
                x: margin + indent + markerWidth, y: yPos,
                maxWidth: maxWidth - indent - markerWidth,
                fontSize: 10, lineHeight: 4.5, ensureSpace
            });
            yPos += 1;
        } else if (element.type === 'table') {
            const cellPadding = 2;
            const minCellHeight = 6;
            const lineHeight = 4;
            const numCols = element.rows[0]?.length || 1;
            const colWidth = maxWidth / numCols;
            const textWidth = colWidth - (cellPadding * 2);

            element.rows.forEach((row, rowIndex) => {
                const fontSize = rowIndex === 0 ? 9 : 8;
                const cellLines = row.map(cell => withFontSize(
                    layoutRuns(pdf, headerAwareRuns(cell.runs, rowIndex === 0), textWidth, fontSize),
                    fontSize
                ));
                const maxLinesInRow = Math.max(1, ...cellLines.map(lines => lines.length));
                const rowHeight = Math.max(minCellHeight, maxLinesInRow * lineHeight + cellPadding * 2);

                yPos = ensureSpace(yPos, rowHeight);

                row.forEach((cell, colIndex) => {
                    const x = margin + (colIndex * colWidth);

                    pdf.setFillColor(...(rowIndex === 0 ? [240, 240, 240] : [255, 255, 255]));
                    pdf.setDrawColor(180, 180, 180);
                    pdf.setLineWidth(0.3);
                    pdf.rect(x, yPos, colWidth, rowHeight, 'FD');

                    drawRunLines(pdf, cellLines[colIndex], {
                        x: x + cellPadding,
                        y: yPos + cellPadding + lineHeight,
                        lineHeight
                    });
                });

                yPos += rowHeight;
            });

            yPos += 5;
            pdf.setFont('helvetica', 'normal');
            pdf.setDrawColor(0, 0, 0);
        } else if (element.type === 'code') {
            if (element.language === 'mermaid') {
                const diagram = diagramMap[index];
                if (diagram) {
                    const imageMaxWidth = maxWidth - 20;
                    const aspectRatio = diagram.height / diagram.width;
                    const imageWidth = Math.min(diagram.width * 0.264583, imageMaxWidth);
                    const imageHeight = imageWidth * aspectRatio;

                    yPos = ensureSpace(yPos, imageHeight + 10);
                    pdf.addImage(diagram.dataUrl, 'PNG', margin + 10, yPos, imageWidth, imageHeight);
                    yPos += imageHeight + 10;
                } else {
                    yPos = ensureSpace(yPos, 10);
                    pdf.setFontSize(9);
                    pdf.setFont('helvetica', 'italic');
                    pdf.text('[Mermaid Diagram - see online version for visualization]', margin, yPos);
                    yPos += 8;
                    pdf.setFont('helvetica', 'normal');
                }
            } else {
                // Every other fenced block used to be dropped on the floor here, even though
                // the website renders it.
                const codeRuns = [{ text: element.content, code: true }];
                const lines = withFontSize(layoutRuns(pdf, codeRuns, maxWidth - 12, 8), 8);

                yPos = ensureSpace(yPos, Math.min(lines.length, 4) * 4 + 4);
                pdf.setFillColor(246, 246, 246);
                pdf.rect(margin, yPos - 4, maxWidth, lines.length * 4 + 3, 'F');
                yPos = drawRunLines(pdf, lines, { x: margin + 3, y: yPos, lineHeight: 4, ensureSpace });
                yPos += 4;
            }
        } else if (element.type === 'hr') {
            yPos = ensureSpace(yPos, 5);
            pdf.setDrawColor(0, 0, 0);
            pdf.setLineWidth(0.2);
            pdf.line(margin, yPos, pageWidth - margin, yPos);
            yPos += 5;
        }
    });

    return pdf;
};

const headerAwareRuns = (runs, isHeader) => (
    isHeader ? (runs || []).map(run => ({ ...run, bold: true })) : (runs || [])
);

// Export to PDF
export const exportToPDF = async (markdown, filename = 'report.pdf') => {
    try {
        const pdf = await buildPdfDocument(markdown);
        pdf.save(filename);
        return { success: true };
    } catch (error) {
        console.error('PDF export error:', error);
        return { success: false, error: error.message };
    }
};

// ---------------------------------------------------------------------------------------
// Word rendering
// ---------------------------------------------------------------------------------------

const HEADING_LEVELS = [
    HeadingLevel.HEADING_1,
    HeadingLevel.HEADING_2,
    HeadingLevel.HEADING_3,
    HeadingLevel.HEADING_4,
    HeadingLevel.HEADING_5
];

const docxTextRuns = (runs, extra = {}) => (runs || []).flatMap(run => {
    const text = sanitizeForDocx(run.text);
    if (!text) return [];

    // A TextRun does not interpret newlines; docx needs an explicit break.
    return text.split('\n').map((segment, index) => new TextRun({
        text: segment,
        bold: !!(run.bold || extra.bold),
        italics: !!(run.italic || extra.italics),
        strike: !!run.strike,
        ...(run.code ? { font: 'Courier New' } : {}),
        ...(run.link ? { color: '0563C1', underline: {} } : {}),
        ...(index > 0 ? { break: 1 } : {})
    }));
});

// Consecutive runs sharing a URL become one clickable hyperlink, as on the website.
const docxChildren = (runs, extra = {}) => {
    const children = [];
    let index = 0;

    while (index < (runs || []).length) {
        const link = runs[index].link;

        if (!link) {
            children.push(...docxTextRuns([runs[index]], extra));
            index++;
            continue;
        }

        const group = [];
        while (index < runs.length && runs[index].link === link) group.push(runs[index++]);
        children.push(new ExternalHyperlink({ children: docxTextRuns(group, extra), link }));
    }

    return children;
};

/**
 * Build the Word document. Separated from exportToWord so the bytes can be produced and
 * inspected without a browser download.
 */
export const buildWordDocument = async (markdown, options = {}) => {
    const structure = parseMarkdownToStructure(markdown);
    const diagramMap = options.diagramMap || await preRenderMermaidDiagrams(structure);
    const children = [];

    structure.forEach((element, elementIndex) => {
        if (element.type === 'heading') {
            children.push(new Paragraph({
                children: docxChildren(element.runs),
                heading: HEADING_LEVELS[Math.min(element.level, HEADING_LEVELS.length) - 1],
                spacing: { before: 240, after: 120 }
            }));
        } else if (element.type === 'paragraph') {
            children.push(new Paragraph({
                children: docxChildren(element.runs, element.blockquote ? { italics: true } : {}),
                spacing: { after: 120 },
                ...(element.blockquote ? { indent: { left: 360 } } : {})
            }));
        } else if (element.type === 'list') {
            children.push(new Paragraph({
                children: [
                    new TextRun(`${element.marker} `),
                    ...docxChildren(element.runs)
                ],
                spacing: { after: 60 },
                indent: { left: 360 * ((element.depth || 0) + 1) }
            }));
        } else if (element.type === 'table') {
            const tableRows = element.rows.map((row, rowIndex) => new TableRow({
                children: row.map(cell => new TableCell({
                    children: [new Paragraph({
                        children: docxChildren(headerAwareRuns(cell.runs, rowIndex === 0))
                    })],
                    shading: rowIndex === 0 ? { fill: 'F0F0F0' } : undefined,
                    width: { size: 100 / row.length, type: WidthType.PERCENTAGE }
                }))
            }));

            children.push(new Table({ rows: tableRows, width: { size: 100, type: WidthType.PERCENTAGE } }));
            children.push(new Paragraph({ text: '', spacing: { after: 200 } }));
        } else if (element.type === 'code') {
            if (element.language === 'mermaid') {
                const diagram = diagramMap[elementIndex];
                if (diagram && diagram.dataUrl) {
                    const base64Data = diagram.dataUrl.split(',')[1];
                    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

                    const maxWidth = 576;
                    const scale = diagram.width > maxWidth ? maxWidth / diagram.width : 1;

                    children.push(new Paragraph({
                        children: [new ImageRun({
                            data: imageBuffer,
                            transformation: {
                                width: diagram.width * scale,
                                height: diagram.height * scale
                            }
                        })],
                        spacing: { before: 120, after: 120 }
                    }));
                } else {
                    children.push(new Paragraph({
                        children: [new TextRun({
                            text: '[Mermaid Diagram - see online version for visualization]',
                            italics: true
                        })],
                        spacing: { after: 120 }
                    }));
                }
            } else {
                // Every other fenced block used to be dropped on the floor here, even though
                // the website renders it.
                children.push(new Paragraph({
                    children: docxTextRuns([{ text: element.content, code: true }]),
                    spacing: { before: 120, after: 120 },
                    indent: { left: 360 },
                    shading: { fill: 'F6F6F6' }
                }));
            }
        } else if (element.type === 'hr') {
            children.push(new Paragraph({
                text: '_______________________________________________',
                spacing: { before: 120, after: 120 }
            }));
        }
    });

    return new Document({
        sections: [{
            properties: {
                page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } }
            },
            children
        }]
    });
};

// Export to Word
export const exportToWord = async (markdown, filename = 'report.docx') => {
    try {
        const doc = await buildWordDocument(markdown);
        const blob = await Packer.toBlob(doc);
        fileSaver.saveAs(blob, filename);
        return { success: true };
    } catch (error) {
        console.error('Word export error:', error);
        return { success: false, error: error.message };
    }
};

export { sanitizeForDocx, normalizeUnicode };
